### ISSUE TITLE
Get Unit Files Written for Layer 2 Services

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#227]

**Comment by StevenIsaacs** [comment]
The unit files have been written and at the same time added files for the new layer 1 services. I also modified all services to use config files rather than rely upon hard coded command lines. Most of the services start. statspusher and kv are not yet happy. Apparently there's some config magic still needed for them. The files have been pushed to a checkpoint in the 227_cerana_unit_files branch of the nixpkgs repo.
