### ISSUE TITLE
Containerize Build Process

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#35]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Thu Feb 25 16:39:25 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/35_

---
# Epic Description

Out of 1/4/16 sprint planning and follow-on conversations between Josh and Ferzan. We want to put the build process with jenkins inside a container that we can commit with our codebase.
The purpose of this epic is to aggregate the tasks associated with this endeavor starting with a Proof-Of-Concept that will lay the roadmap for necessary tasks and potential issues.

**Comment by pjnorton** [comment]
Working on the Ubuntu 14.04 container.

**Comment by StevenIsaacs** [comment]
The container now runs on Ubuntu 14.04. Because of problems related to GMP I changed the SDK to include gcc version 5.3.0. This introduced new problem when building Mistify-OS within the Mistify-SDK container multilib no longer works (used for building grub and the ISO). I disabled that to see if the build would finish and encountered a problem with python complaining about missing modules.
